version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_notes
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  node-app:
    image: node:latest
    container_name: notes_app
    working_dir: /server
    volumes:
      - ../server:/server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ["npm", "run", "start:dev"]
    env_file:
      - ../server/.env

volumes:
  pg_data:

